version: "3"
services:
  snail:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/db
    networks:
      - snail
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017"
    networks:
      - snail

networks:
  snail:
    driver: bridge
